/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package composite;

import javax.swing.DefaultListModel;

/**
 *
 * @author ACER
 */
public class Pencere extends javax.swing.JFrame {

    /**
     * Creates new form Pencere
     */
    public Pencere() {
        initComponents();
    }

    DefaultListModel dm = new DefaultListModel();

    public void addData(String name) {
        jList1.setModel(dm);
        dm.addElement(name);
    }

    public void yemekEkle(String name) {
        jList1.setModel(dm);
        int totalIndex = dm.size();
        int foodIndex = 0;
        for (int i = 0; i < totalIndex; i++) {
            if (dm.getElementAt(i).toString() == "-Yiyecekler") {
                foodIndex = i;
            }
        }
        dm.add(foodIndex + 1, name);
    }

    public void icecekEkle(String name) {
        jList1.setModel(dm);
        int totalIndex = dm.size();
        int foodIndex = 0;
        for (int i = 0; i < totalIndex; i++) {
            if (dm.getElementAt(i).toString() == "-İçecekler") {
                foodIndex = i;
            }
        }
        dm.add(foodIndex + 1, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yiyecekIsmi = new javax.swing.JTextField();
        yiyecekFiyat = new javax.swing.JTextField();
        icecekIsmi = new javax.swing.JTextField();
        icecekFiyat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        altKategori = new javax.swing.JTextField();
        yiyecekEkle = new javax.swing.JButton();
        icecekEkle = new javax.swing.JButton();
        altMenuEkle = new javax.swing.JButton();
        silBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menü");

        jLabel2.setText("İçerik Ekle");

        jLabel3.setText("Yemek İsmi:");

        jLabel4.setText("Yemek Fiyatı:");

        jLabel5.setText("İçecek İsmi:");

        jLabel6.setText("İçecek Fiyatı:");

        yiyecekIsmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yiyecekIsmiActionPerformed(evt);
            }
        });

        jLabel7.setText("Alt Menü:");

        yiyecekEkle.setText("Ekle");
        yiyecekEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yiyecekEkleActionPerformed(evt);
            }
        });

        icecekEkle.setText("Ekle");
        icecekEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecekEkleActionPerformed(evt);
            }
        });

        altMenuEkle.setText("Ekle");
        altMenuEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altMenuEkleActionPerformed(evt);
            }
        });

        silBtn.setText("Sil");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        jList1.setModel(dm);
        jList1.setToolTipText("");
        dm.addElement("---MENU---");
        dm.addElement("-Yiyecekler");
        dm.addElement("Karnıyarık -> 25 Lira");
        dm.addElement("İskender -> 35 Lira");
        dm.addElement("Köfte -> 25 Lira");
        dm.addElement("-İçecekler");
        dm.addElement("Ayran -> 2 Lira");
        dm.addElement("Kola -> 8 Lira");
        dm.addElement("Şalgam -> 5 Lira");
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(silBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(icecekFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(icecekIsmi)
                                        .addComponent(yiyecekFiyat)
                                        .addComponent(yiyecekIsmi))
                                    .addComponent(altKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yiyecekEkle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(icecekEkle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(altMenuEkle, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(yiyecekIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(yiyecekFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yiyecekEkle)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(icecekIsmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(icecekFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icecekEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(altKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altMenuEkle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(silBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String yiyecekIsmiEtx, yiyecekFiyatEtx;
    String icecekIsmiEtx, icecekFiyatEtx;
    String altKategoriEtx;

    Kategori items = new Kategori("Menü");

    //alt kategoriler
    Kategori yiyecekler = new Kategori("Yiyecekler");
    Kategori icecekler = new Kategori("İçecekler");

    private void yiyecekIsmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yiyecekIsmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yiyecekIsmiActionPerformed

    private void icecekEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecekEkleActionPerformed
        // TODO add your handling code here:
        icecekIsmiEtx = icecekIsmi.getText().toString();
        icecekFiyatEtx = icecekFiyat.getText().toString();

        Urunler icecekInputGonder = new Urunler(icecekIsmiEtx, icecekFiyatEtx);
        icecekler.add(icecekInputGonder);
        icecekEkle(icecekIsmiEtx + " -> " + icecekFiyatEtx + " Lira");
        System.out.println("İcecek: " + icecekIsmiEtx + " ₺" + icecekFiyatEtx + " lira olarak eklendi.");
        //

    }//GEN-LAST:event_icecekEkleActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        if (jList1.getSelectedValue().toString().charAt(0) != '-') {
            dm.removeElementAt(index);
        } else {
            System.out.println("Bunlar silinemez");
        }
    }//GEN-LAST:event_silBtnActionPerformed

    private void yiyecekEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yiyecekEkleActionPerformed
        // TODO add your handling code here:
        yiyecekIsmiEtx = yiyecekIsmi.getText().toString();
        yiyecekFiyatEtx = yiyecekFiyat.getText().toString();

        Urunler yiyecekInputGonder = new Urunler(yiyecekIsmiEtx, yiyecekFiyatEtx);
        yiyecekler.add(yiyecekInputGonder);
        yemekEkle(yiyecekIsmiEtx + " -> " + yiyecekFiyatEtx + " Lira");
        System.out.println(dm.size());;
        System.out.println("Yiyecek: " + yiyecekIsmiEtx + " ₺" + yiyecekFiyatEtx + " lira olarak eklendi.");

        //

    }//GEN-LAST:event_yiyecekEkleActionPerformed

    private void altMenuEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altMenuEkleActionPerformed
        // TODO add your handling code here:
        altKategoriEtx = altKategori.getText().toString();
        
        Kategori yeniKategoriGonder = new Kategori(altKategoriEtx);
        dm.addElement("*"+altKategoriEtx);
        System.out.println("Kategori: " + altKategoriEtx + " başarıyla eklendi.");
    }//GEN-LAST:event_altMenuEkleActionPerformed

                                                
       
         
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencere().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altKategori;
    private javax.swing.JButton altMenuEkle;
    private javax.swing.JButton icecekEkle;
    private javax.swing.JTextField icecekFiyat;
    private javax.swing.JTextField icecekIsmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton silBtn;
    private javax.swing.JButton yiyecekEkle;
    private javax.swing.JTextField yiyecekFiyat;
    private javax.swing.JTextField yiyecekIsmi;
    // End of variables declaration//GEN-END:variables
}
